# Generated by Django 4.2.2 on 2023-06-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_publication_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.FileField(blank='true', null='True', upload_to='profile_pictures'),
            preserve_default='True',
        ),
    ]
